#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-editables
Version  : 0.2
Release  : 1
URL      : https://files.pythonhosted.org/packages/e4/b8/4cbc098360011c019ded1b66bcf7ab777cfbce457d5f637b7880d13768ac/editables-0.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/e4/b8/4cbc098360011c019ded1b66bcf7ab777cfbce457d5f637b7880d13768ac/editables-0.2.tar.gz
Summary  : Editable installations
Group    : Development/Tools
License  : MIT
Requires: pypi-editables-python = %{version}-%{release}
Requires: pypi-editables-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
This library supports the building of wheels which, when installed, will
        expose packages in a local directory on `sys.path` in "editable mode". In
        other words, changes to the package source will be  reflected in the package
        visible to Python, without needing a reinstall.
        
        ## Usage
        
        Suppose you want to build a wheel for your project `foo`. Your project is
        located in the directory `/path/to/foo`. Under that directory, you have a
        `src` directory containing your project, which is a package called `foo`
        and a Python module called `bar.py`. So your directory structure looks like

%package python
Summary: python components for the pypi-editables package.
Group: Default
Requires: pypi-editables-python3 = %{version}-%{release}

%description python
python components for the pypi-editables package.


%package python3
Summary: python3 components for the pypi-editables package.
Group: Default
Requires: python3-core
Provides: pypi(editables)

%description python3
python3 components for the pypi-editables package.


%prep
%setup -q -n editables-0.2
cd %{_builddir}/editables-0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1647299364
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
